services:
  - type: web
    name: agricultural-logistics-api
    env: ruby
    region: frankfurt # or oregon, frankfurt, singapore
    plan: free
    buildCommand: "bundle install && bundle exec rake assets:precompile"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "false"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: agricultural-logistics-db
          property: connectionString

databases:
  - name: agricultural-logistics-db
    databaseName: agricultural_logistics_production
    user: agricultural_logistics
    plan: free
