databases:
  - name: agricultural-logistics-db
    databaseName: agricultural_logistics
    user: agricultural_logistics
    plan: free

services:
  - type: web
    name: agricultural-logistics
    runtime: ruby
    plan: free
    rootDir: .
    # buildCommand: "bundle install && bundle exec rake assets:precompile && bundle exec rake assets:clean && bundle exec rake db:migrate"
    buildCommand: "bundle install && bundle exec rake assets:precompile && bundle exec rake db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agricultural-logistics-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
